#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

current_branch=$(git rev-parse --abbrev-ref HEAD)
if [[ "$current_branch" == "main" || "$current_branch" == "master" ]]; then
    echo "[Husky] ERROR: You cannot push to the $current_branch branch."
    exit 1
    fi